### ISSUE TITLE
Assistance on writing in Ember

### ISSUE THREAD

**Issue by carrotsimon** [null-null-null/ember-animejs#1]
Hi!

Is it possible to expand on writing a real world example for use of this? As a newer dev I'm having difficulty using this in ember with the supplied usage example. Would it possible for someone to write a direct example of how this animation would be written in ember-animejs? http://animejs.com/documentation/#domAttributes

I hope you can help!

Simon

**Comment by carrotsimon** [comment]
Forgive me, I'm closing this as I realised it's not an issue and this isn't the best place for this request!

**Comment by briarsweetbriar** [comment]
No worries!
